[versions]
room = "2.8.4"
litert = "2.1.0"

[libraries]
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
google-ai-edge-litert = { module = "com.google.ai.edge.litert:litert", version.ref = "litert" }
